const brandOptions = [
    { value: "", label: "No brand" },

    { value: "Unknown", label: "Unknown" },
    { value: "Coca Cola", label: "Coca Cola" },
    { value: "Sprite", label: "Sprite" },
    { value: "Starbucks", label: "Starbucks" },
    { value: "Folgers", label: "Folgers" },
    { value: "Nestle", label: "Nestle" },
    { value: "V8", label: "V8" },
    { value: "Lipton", label: "Lipton" },
    { value: "Arizona", label: "Arizona" },
    { value: "Gatorade", label: "Gatorade" },
    { value: "Aquafina", label: "Aquafina" },
    { value: "Dasani", label: "Dasani" },
    { value: "Budweiser", label: "Budweiser" },
    { value: "Modelo", label: "Modelo" },
    { value: "Michelob", label: "Michelob" },
    { value: "Corona", label: "Corona" },
    { value: "Heineken", label: "Heineken" },
    { value: "Miller", label: "Miller" },
    { value: "Blue Moon", label: "Blue Moon" },
    { value: "Kirkland", label: "Kirkland" },
    { value: "Kroger", label: "Kroger" },
    { value: "Great Value (Walmart)", label: "Great Value (Walmart)" },
    { value: "Trader Joe's", label: "Trader Joe's" },
    { value: "Colgate Palmolive", label: "Colgate Palmolive" },
    { value: "Crest", label: "Crest" },
    { value: "Arm and Hammer", label: "Arm and Hammer" },
    { value: "Clorox", label: "Clorox" },
    { value: "Lysol", label: "Lysol" },
    { value: "Tide", label: "Tide" },
    { value: "Downy", label: "Downy" },
    { value: "Oxi Clean", label: "Oxi Clean" },
    { value: "Kelloggs", label: "Kelloggs" },
    { value: "Campbells", label: "Campbells" },
    { value: "Dole", label: "Dole" },
    { value: "Nabisco", label: "Nabisco" },
    { value: "Barilla", label: "Barilla" },
    { value: "Lays", label: "Lays" },
    { value: "Pringles", label: "Pringles" },
    { value: "Betty Crocker", label: "Betty Crocker" },

    // Other
    { value: "Other", label: "Other (Specify Below)" },
];

export default brandOptions;
