const shapeOptions = [
    { value: "can", label: "Can" },
    { value: "tube", label: "Tube" },
    { value: "box", label: "Box" },
    { value: "bag", label: "Bag" },
    { value: "paper", label: "Paper" },
    { value: "bottle", label: "Bottle" },
    { value: "cup", label: "Cup" },
    { value: "straw", label: "Straw" },
    { value: "foil", label: "Foil" },
    { value: "wrapper", label: "Wrapper" },
    { value: "roll", label: "Roll" },
    { value: "sheet", label: "Sheet" },
    { value: "tray", label: "Tray" },
    { value: "pouch", label: "Pouch" },
    { value: "packet", label: "Packet" },
    { value: "blister pack", label: "Blister Pack" },
    { value: "sachet", label: "Sachet" },
    { value: "envelope", label: "Envelope" },
    { value: "cylinder", label: "Cylinder" },
    { value: "disc", label: "Disc" },
    { value: "stick", label: "Stick" },
    { value: "mesh", label: "Mesh" },
    { value: "coil", label: "Coil" },
    { value: "fragment", label: "Fragment" },
    { value: "lid", label: "Lid" },
    { value: "cap", label: "Cap" },
    { value: "other", label: "Other" },
];

export default shapeOptions;
